inherit_from: .rubocop_todo.yml

# rubocop configuration

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
  Exclude:
    - 'blocklistshow.gemspec'

Layout/SpaceInsideParens:
  EnforcedStyle: space
  Exclude:
    - 'blocklistshow.gemspec'

Layout/SpaceInsideRangeLiteral:
  #EnforcedStyle: space
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: space
  Exclude:
    - 'blocklistshow.gemspec'

Metrics/LineLength:
  Exclude:
    - 'blocklistshow.gemspec'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

